use_frameworks!

platform :ios, '9.0'

target 'iVisual_Example' do
  pod 'iVisual', :path => '../'

  pod 'SnapKit'
  pod 'FileBox', '~> 0.4.1'
  
  target 'iVisual_Tests' do
    inherit! :search_paths

    
  end
end
